### PR TITLE
Implement off

### PR DESCRIPTION
**Pull request by marc-costello**

### CODE REVIEW

**Comment by marc-costello** [comment]
There quite a bit in here.. Much more than just implementing off().

**Comment by richarddowson** [comment]
Looks good, except that removeEventListener will fail; the addEventListener is called passing a proxy handler, removeEventListener is called with the user-supplied handler.

**Comment by marc-costello** [comment]
Yea looks like we will have to cache the user defined handler along with our proxy handler. If only for this use case

**Comment by marc-costello** [comment]
@richarddowson I've added the proxyHandler to the cache, along side the user defined.

**Pull request merged**
